# Generated by Django 4.0.1 on 2022-02-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hirurg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Ф.И.О - Врача')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('skill', models.TextField(verbose_name='Стаж работы')),
                ('number', models.CharField(max_length=30, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Госпиталя')),
                ('descriptions', models.TextField(unique=True, verbose_name='Описание')),
                ('region_name', models.CharField(max_length=100, verbose_name='Регион')),
                ('city_name', models.CharField(max_length=100, verbose_name='Город')),
                ('category', models.BooleanField(default=False, verbose_name='Выбор: -')),
            ],
        ),
        migrations.CreateModel(
            name='Terapevt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О - Врача')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('skill', models.TextField(verbose_name='Опыт работы')),
                ('number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О - Пациента')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('Reason_for_going_to_the_hospital', models.TextField(verbose_name='Причина обращения в больницу')),
                ('number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Medsestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О - Медсестры')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('access_to_hirurg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='building.hirurg')),
                ('access_to_terapevt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='building.terapevt')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='hirurg',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.hospital'),
        ),
        migrations.CreateModel(
            name='GlavVrach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О Глав-Врача')),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Возраст')),
                ('number', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.hospital')),
            ],
        ),
    ]
